import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "~/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "記事作成",
  description: "Generated by create next app",
};

export default function CreateLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Header
          breadcrumbList={[
            { title: "いっせいブログ", path: "/" },
            { title: "記事作成", path: "" },
          ]}
        />
        {children}
      </body>
    </html>
  );
}
